package org.dreambot.api.script;

public enum Category
{
	AGILITY, COMBAT, CONSTRUCTION, COOKING, CRAFTING, FARMING, FIREMAKING,
	FISHING, FLETCHING, HERBLORE, HUNTING, MAGIC, MINIGAME, MINING,
	MISC, MONEYMAKING, PRAYER, QUEST, RUNECRAFTING, SLAYER, SMITHING,
	THIEVING, WOODCUTTING, UTILITY
}
